version: "3"

services:
  redis:
    image: redis:latest
    sysctls:
      - net.core.somaxconn=1024

    volumes:
      - redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./.run/redis:/var/run/redis
    command: bash -c "redis-server /usr/local/etc/redis/redis.conf"

  web:
    build: ./web
    command: sh -c "gunicorn --bind unix:/var/run/gunicorn/uvicorn.sock multichat.asgi:application -w 2 -k uvicorn.workers.UvicornWorker"
    volumes:
      - ./web:/usr/src/app
      - ./.run/gunicorn:/var/run/gunicorn
      - ./.run/redis:/var/run/redis
      - ./.run/postgresql:/var/run/postgresql
    links:
      - redis

  nginx:
    image: nginx
    # restart: always
    ports:
      - "80:80"
    volumes:
      - ./web/static:/var/www/app/static        # 這裡把web (也就是django)的static files放在nginx中。
      - ./.run/gunicorn:/var/run/gunicorn
      - ./nginx/conf.d:/etc/nginx/conf.d

  postgres:
    image: postgres:11.2-alpine
    # container_name: postgres
    container_name: postgres11-multichat
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - ./.run/postgresql:/var/run/postgresql

volumes: 
  redisdata: